// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhtW9cTGYTc4ULmqLU6-fS_x9EjUJbA7Y',
    appId: '1:758332049533:web:cc3fd69ef0d3a8e1620914',
    messagingSenderId: '758332049533',
    projectId: 'alarmku-94cea',
    authDomain: 'alarmku-94cea.firebaseapp.com',
    storageBucket: 'alarmku-94cea.firebasestorage.app',
    measurementId: 'G-0C9XBFZ577',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKitFHRrc6-9Fh3y06ArN53EHBvxlO9HM',
    appId: '1:758332049533:android:f1d9b9d8e89b80a5620914',
    messagingSenderId: '758332049533',
    projectId: 'alarmku-94cea',
    storageBucket: 'alarmku-94cea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1mFo3Uas7GZX3blRvIYip3s3dUoQmd7k',
    appId: '1:758332049533:ios:2a445c5f7f254b03620914',
    messagingSenderId: '758332049533',
    projectId: 'alarmku-94cea',
    storageBucket: 'alarmku-94cea.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiAlarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1mFo3Uas7GZX3blRvIYip3s3dUoQmd7k',
    appId: '1:758332049533:ios:2a445c5f7f254b03620914',
    messagingSenderId: '758332049533',
    projectId: 'alarmku-94cea',
    storageBucket: 'alarmku-94cea.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiAlarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhtW9cTGYTc4ULmqLU6-fS_x9EjUJbA7Y',
    appId: '1:758332049533:web:77116a63cc3864f2620914',
    messagingSenderId: '758332049533',
    projectId: 'alarmku-94cea',
    authDomain: 'alarmku-94cea.firebaseapp.com',
    storageBucket: 'alarmku-94cea.firebasestorage.app',
    measurementId: 'G-XG1STSCZJ7',
  );
}
